version = 1
[custom]
enable_rule_generator = false
overwrite_original_rules = false


[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]æ–°åŠ å¡èŠ‚ç‚¹", "[]ç¾å›½èŠ‚ç‚¹", ".*", "[]DIRECT"]


[[custom_groups]]
name = "æ–°åŠ å¡èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|ã€SGã€‘|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true


[[custom_groups]]
name = "ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ã€USã€‘|ç¾)"]
url = "http://www.gstatic.com/generate_204"
interval = 300
tolerance = 150
lazy = true


[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/aiden262/Backup/main/proxy.list"
