version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

[[custom_groups]]
name = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
type = "select"
rule = ["[]ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹", "[]ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹", ".*", "[]DIRECT"]

[[custom_groups]]
name = "ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹"
type = "url-test"
rule = ["(æ–°åŠ å¡|å¡|ç‹®åŸ|ã€SGã€‘|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
tolerance = 60
lazy = true


[[custom_groups]]
name = "ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹"
type = "url-test"
rule = ["(ã€USã€‘CF|ã€USã€‘GCORE|ç¾)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
tolerance = 60
lazy = true

[[custom_groups]]
name = "ğŸ¤ å…¬ç›ŠèŠ‚ç‚¹"
type = "url-test"
rule = ["(RN|CCS|WAP)"]
url = "http://www.gstatic.com/generate_204"
interval = 600
tolerance = 150
lazy = true


[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/aiden262/Backup/main/proxy.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸš€ èŠ‚ç‚¹é€‰æ‹©"
ruleset = "[]FINAL"
